/*
 * photon-indexer
 *
 * Solana indexer for general compression
 *
 * The version of the OpenAPI document: 0.28.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AccountState {
    #[serde(rename = "initialized")]
    Initialized,
    #[serde(rename = "frozen")]
    Frozen,
}

impl ToString for AccountState {
    fn to_string(&self) -> String {
        match self {
            Self::Initialized => String::from("initialized"),
            Self::Frozen => String::from("frozen"),
        }
    }
}

impl Default for AccountState {
    fn default() -> AccountState {
        Self::Initialized
    }
}
