/*
 * photon-indexer
 *
 * Solana indexer for general compression
 *
 * The version of the OpenAPI document: 0.28.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Context {
    #[serde(rename = "slot")]
    pub slot: i32,
}

impl Context {
    pub fn new(slot: i32) -> Context {
        Context { slot }
    }
}
