/*
 * photon-indexer
 *
 * Solana indexer for general compression
 *
 * The version of the OpenAPI document: 0.28.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignatureInfo {
    /// An Unix timestamp (seconds)
    #[serde(rename = "blockTime")]
    pub block_time: i32,
    /// A Solana transaction signature.
    #[serde(rename = "signature")]
    pub signature: String,
    #[serde(rename = "slot")]
    pub slot: i32,
}

impl SignatureInfo {
    pub fn new(block_time: i32, signature: String, slot: i32) -> SignatureInfo {
        SignatureInfo {
            block_time,
            signature,
            slot,
        }
    }
}
