/*
 * photon-indexer
 *
 * Solana indexer for general compression
 *
 * The version of the OpenAPI document: 0.28.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenAcccount {
    #[serde(rename = "account")]
    pub account: Box<models::Account>,
    #[serde(rename = "tokenData")]
    pub token_data: Box<models::TokenData>,
}

impl TokenAcccount {
    pub fn new(account: models::Account, token_data: models::TokenData) -> TokenAcccount {
        TokenAcccount {
            account: Box::new(account),
            token_data: Box::new(token_data),
        }
    }
}
