/*
 * photon-indexer
 *
 * Solana indexer for general compression
 *
 * The version of the OpenAPI document: 0.28.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenAccountBalance {
    #[serde(rename = "amount")]
    pub amount: i32,
}

impl TokenAccountBalance {
    pub fn new(amount: i32) -> TokenAccountBalance {
        TokenAccountBalance { amount }
    }
}
