# Light Protocol - JavaScript Packages

default:
    @just --list

build:
    cd stateless.js && pnpm build
    cd compressed-token && pnpm build

build-token-kit:
    cd token-kit && pnpm build

test: test-stateless test-compressed-token

test-stateless:
    cd stateless.js && pnpm test

test-compressed-token:
    cd compressed-token && pnpm test

test-compressed-token-unit-v2:
    cd compressed-token && pnpm test:unit:all:v2

test-token-kit:
    cd token-kit && pnpm test

start-validator:
    ./../cli/test_bin/run test-validator

test-token-kit-e2e: start-validator
    cd token-kit && LIGHT_PROTOCOL_VERSION=V2 LIGHT_PROTOCOL_BETA=true pnpm test:e2e

lint:
    cd stateless.js && pnpm lint
    cd compressed-token && pnpm lint

lint-token-kit:
    cd token-kit && pnpm lint

format:
    cd stateless.js && pnpm format
    cd compressed-token && pnpm format
