//! Minimal test program for #[light_account(init)] PDA macro validation.
//!
//! This program tests ONLY the compressible PDA creation macro in isolation,
//! ensuring the simplest PDA-only program compiles and works correctly.

#![allow(deprecated)]

use anchor_lang::prelude::*;
use light_account::{derive_light_cpi_signer, light_program, CpiSigner};

pub mod instruction_accounts;
pub mod state;

pub use instruction_accounts::*;
pub use state::*;

declare_id!("PdaT111111111111111111111111111111111111111");

pub const LIGHT_CPI_SIGNER: CpiSigner =
    derive_light_cpi_signer!("PdaT111111111111111111111111111111111111111");

#[light_program]
#[program]
pub mod single_pda_test {
    use super::*;

    /// Create a single compressible PDA.
    /// The account is created by Anchor and made compressible by the
    /// LightFinalize trait implementation generated by #[light_account(init)].
    pub fn create_pda<'info>(
        ctx: Context<'_, '_, '_, 'info, CreatePda<'info>>,
        params: CreatePdaParams,
    ) -> Result<()> {
        ctx.accounts.record.owner = params.owner;
        Ok(())
    }
}
