//! D5 Test: Token account creation with authority seeds (mark-only mode)
//!
//! Tests mark-only token accounts - the derive generates seed structs and variant
//! enums for decompression, but the token account is created manually via
//! CreateTokenAccountCpi in the instruction handler.

use anchor_lang::prelude::*;
use light_sdk_macros::LightAccounts;
use light_account::{LIGHT_TOKEN_CONFIG, LIGHT_TOKEN_RENT_SPONSOR};

pub const D5_VAULT_AUTH_SEED: &[u8] = b"d5_vault_auth";
pub const D5_VAULT_SEED: &[u8] = b"d5_vault";

#[derive(AnchorSerialize, AnchorDeserialize, Clone, Debug)]
pub struct D5LightTokenParams {
    pub vault_bump: u8,
}

/// Tests mark-only token account with authority seeds.
/// #[derive(LightAccounts)] generates no-op LightPreInit/LightFinalize impls.
/// Seed structs and variant enums are generated by #[light_program].
#[derive(Accounts, LightAccounts)]
#[instruction(params: D5LightTokenParams)]
pub struct D5LightToken<'info> {
    #[account(mut)]
    pub fee_payer: Signer<'info>,

    /// CHECK: Token mint
    pub mint: AccountInfo<'info>,

    #[account(
        seeds = [D5_VAULT_AUTH_SEED],
        bump,
    )]
    pub vault_authority: UncheckedAccount<'info>,

    #[account(
        mut,
        seeds = [D5_VAULT_SEED, mint.key().as_ref()],
        bump,
    )]
    // Mark-only: seeds and owner_seeds only (no mint/owner)
    // Token vault - created manually via CreateTokenAccountCpi in handler
    #[light_account(token::seeds = [D5_VAULT_SEED, self.mint.key()], token::owner_seeds = [D5_VAULT_AUTH_SEED])]
    pub d5_token_vault: UncheckedAccount<'info>,

    #[account(address = LIGHT_TOKEN_CONFIG)]
    pub light_token_config: AccountInfo<'info>,

    #[account(mut, address = LIGHT_TOKEN_RENT_SPONSOR)]
    pub light_token_rent_sponsor: AccountInfo<'info>,

    /// CHECK: Light token program
    pub light_token_program: AccountInfo<'info>,

    /// CHECK: Light token CPI authority
    pub light_token_cpi_authority: AccountInfo<'info>,

    pub system_program: Program<'info, System>,
}
