//! Program-wide variant enums for compress/decompress dispatch.
//!
//! This module contains the code that would be generated by the `#[light_program]` macro.

use anchor_lang::prelude::*;
use light_sdk::interface::compression_info::CompressedAccountData;
use solana_program_error::ProgramError;

use crate::account_loader::derived_accounts::PackedZeroCopyRecordVariant;
use crate::account_loader::ZeroCopyRecordVariant;
use crate::all::derived_accounts::{
    AllBorshVariant, AllZeroCopyVariant, PackedAllBorshVariant, PackedAllZeroCopyVariant,
};
use crate::pda::derived_accounts::{MinimalRecordVariant, PackedMinimalRecordVariant};
use crate::sdk_functions::decompress::{
    prepare_account_for_decompression, DecompressCtx, DecompressVariant,
};

// ============================================================================
// Program-wide Variant Enums (generated by #[light_program])
// ============================================================================

/// Unpacked variant enum for all account types in this program.
/// Each variant contains the full seeds + data.
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Debug)]
pub enum ProgramAccountVariant {
    MinimalRecord(MinimalRecordVariant),
    ZeroCopyRecord(ZeroCopyRecordVariant),
    AllBorsh(AllBorshVariant),
    AllZeroCopy(AllZeroCopyVariant),
}

/// Packed variant enum for efficient serialization.
/// Does NOT wrap CompressedAccountData - that wrapper is added by the client library.
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Debug)]
pub enum PackedProgramAccountVariant {
    MinimalRecord(PackedMinimalRecordVariant),
    ZeroCopyRecord(PackedZeroCopyRecordVariant),
    AllBorsh(PackedAllBorshVariant),
    AllZeroCopy(PackedAllZeroCopyVariant),
}

/// Type alias matching the client's CompressedAccountData<PackedVariant> structure.
/// This is what the program deserializes from instruction data.
pub type LightAccountData = CompressedAccountData<PackedProgramAccountVariant>;

// ============================================================================
// DecompressVariant Implementation (MACRO-GENERATED)
// ============================================================================

/// Implementation for CompressedAccountData<PackedProgramAccountVariant>.
/// This matches the client library's instruction format.
impl<'info> DecompressVariant<'info> for LightAccountData {
    fn decompress(
        &self,
        pda_account: &AccountInfo<'info>,
        ctx: &mut DecompressCtx<'_, 'info>,
    ) -> std::result::Result<(), ProgramError> {
        match &self.data {
            PackedProgramAccountVariant::MinimalRecord(packed_data) => {
                prepare_account_for_decompression::<4, PackedMinimalRecordVariant>(
                    packed_data,
                    &self.meta,
                    pda_account,
                    ctx,
                )
            }
            PackedProgramAccountVariant::ZeroCopyRecord(packed_data) => {
                prepare_account_for_decompression::<4, PackedZeroCopyRecordVariant>(
                    packed_data,
                    &self.meta,
                    pda_account,
                    ctx,
                )
            }
            PackedProgramAccountVariant::AllBorsh(packed_data) => {
                prepare_account_for_decompression::<3, PackedAllBorshVariant>(
                    packed_data,
                    &self.meta,
                    pda_account,
                    ctx,
                )
            }
            PackedProgramAccountVariant::AllZeroCopy(packed_data) => {
                prepare_account_for_decompression::<3, PackedAllZeroCopyVariant>(
                    packed_data,
                    &self.meta,
                    pda_account,
                    ctx,
                )
            }
        }
    }
}
