//! Program-wide variant enums for compress/decompress dispatch.
//!
//! This module contains the code that would be generated by the `#[light_program]` macro.

use anchor_lang::prelude::*;
use light_sdk::interface::compression_info::CompressedAccountData;
use solana_program_error::ProgramError;

use crate::pda::derived_accounts::{MinimalRecordVariant, PackedMinimalRecordVariant};
use crate::sdk_functions::decompress::{
    prepare_account_for_decompression, DecompressCtx, DecompressVariant,
};

// ============================================================================
// Program-wide Variant Enums (generated by #[light_program])
// ============================================================================

/// Unpacked variant enum for all account types in this program.
/// Each variant contains the full seeds + data.
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Debug)]
pub enum ProgramAccountVariant {
    MinimalRecord(MinimalRecordVariant),
    // Future: OtherRecord(OtherRecordVariant),
}

/// Packed variant enum for efficient serialization.
/// Each variant wraps CompressedAccountData containing packed data + metadata.
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Debug)]
pub enum PackedProgramAccountVariant {
    MinimalRecord(CompressedAccountData<PackedMinimalRecordVariant>),
    // Future: OtherRecord(CompressedAccountData<PackedOtherRecordVariant>),
}

// ============================================================================
// DecompressVariant Implementation (MACRO-GENERATED)
// ============================================================================

impl<'info> DecompressVariant<'info> for PackedProgramAccountVariant {
    fn decompress(
        &self,
        pda_account: &AccountInfo<'info>,
        ctx: &mut DecompressCtx<'_, 'info>,
    ) -> std::result::Result<(), ProgramError> {
        match self {
            PackedProgramAccountVariant::MinimalRecord(account_data) => {
                prepare_account_for_decompression::<3, PackedMinimalRecordVariant>(
                    &account_data.data,
                    &account_data.meta,
                    pda_account,
                    ctx,
                )
            } // Future: PackedProgramAccountVariant::OtherRecord(account_data) => { ... }
        }
    }
}
