//! Macro-derived decompress implementation.
//!
//! This module contains the code that would be generated by the `#[light_program]` macro.
//! With the trait-based dispatch, this module is minimal - just specifies the variant type.

use anchor_lang::prelude::*;

use crate::derived_variants::PackedLightAccountVariant;
use light_sdk::interface::process_decompress_pda_accounts_idempotent;

/// Empty Accounts struct - everything in remaining_accounts.
///
/// MACRO-GENERATED: This struct is the same for all programs.
#[derive(Accounts)]
pub struct DecompressIdempotent {}

/// MACRO-GENERATED: Process handler - forwards to SDK function with program's variant type.
///
/// The SDK's `process_decompress_pda_accounts_idempotent` handles:
/// - Deserializing params (including `CompressedAccountData<PackedLightAccountVariant>`)
/// - Account validation
/// - Trait-based dispatch to prepare_account_for_decompression
/// - CPI to Light System Program
///
/// The type parameter `PackedLightAccountVariant` provides the program-specific
/// dispatch logic via its `DecompressVariant` trait implementation.
pub fn process_decompress_idempotent<'info>(
    remaining_accounts: &[AccountInfo<'info>],
    instruction_data: &[u8],
) -> Result<()> {
    process_decompress_pda_accounts_idempotent::<PackedLightAccountVariant>(
        remaining_accounts,
        instruction_data,
        crate::LIGHT_CPI_SIGNER,
        &crate::ID,
    )
    .map_err(Into::into)
}
