export enum UtxoErrorCode {
  APP_DATA_FROM_BYTES_FUNCTION_UNDEFINED = "APP_DATA_FROM_BYTES_FUNCTION_UNDEFINED",
  INVALID_ASSET_OR_AMOUNTS_LENGTH = "INVALID_ASSET_OR_AMOUNTS_LENGTH",
  EXCEEDED_MAX_ASSETS = "EXCEEDED_MAX_ASSETS",
  NEGATIVE_AMOUNT = "NEGATIVE_AMOUNT",
  NOT_U64 = "NOT_U64",
  BLINDING_EXCEEDS_SIZE = "BLINDING_EXCEEDS_SIZE",
  INDEX_NOT_PROVIDED = "INDEX_NOT_PROVIDED",
  ACCOUNT_HAS_NO_PRIVKEY = "ACCOUNT_HAS_NO_PRIVKEY",
  ASSET_NOT_FOUND = "ASSET_NOT_FOUND",
}

export enum RelayerErrorCode {
  RELAYER_FEE_UNDEFINED = "RELAYER_FEE_UNDEFINED",
  RELAYER_PUBKEY_UNDEFINED = "RELAYER_PUBKEY_UNDEFINED",
  LOOK_UP_TABLE_UNDEFINED = "LOOK_UP_TABLE_UNDEFINED",
  RELAYER_RECIPIENT_UNDEFINED = "RELAYER_RECIPIENT_UNDEFINED",
}

export enum AccountErrorCode {
  INVALID_SEED_SIZE = "INVALID_SEED_SIZE",
  SEED_UNDEFINED = "SEED_UNDEFINED",
  SEED_DEFINED = "SEED_DEFINED",
  ENCRYPTION_PRIVATE_KEY_UNDEFINED = "ENCRYPTION_PRIVATE_KEY_UNDEFINED",
  PRIVATE_KEY_UNDEFINED = "PRIVATE_KEY_UNDEFINED",
  POSEIDON_EDDSA_KEYPAIR_UNDEFINED = "POSEIDON_EDDSA_KEYPAIR_UNDEFINED",
  POSEIDON_EDDSA_GET_PUBKEY_FAILED = "POSEIDON_EDDSA_GET_PUBKEY_FAILED",
  PUBLIC_KEY_UNDEFINED = "PUBLIC_KEY_UNDEFINED",
}

export enum ProviderErrorCode {
  SOL_MERKLE_TREE_UNDEFINED = "SOL_MERKLE_TREE_UNDEFINED",
  ANCHOR_PROVIDER_UNDEFINED = "ANCHOR_PROVIDER_UNDEFINED",
  PROVIDER_UNDEFINED = "PROVIDER_UNDEFINED",
}

export enum VerifierErrorCode {
  PUBLIC_INPUTS_UNDEFINED = "PUBLIC_INPUTS_UNDEFINED",
  INVALID_INPUTS_NUMBER = "INVALID_INPUTS_NUMBER",
  ENCRYPTING_UTXOS_UNDEFINED = "ENCRYPTING_UTXOS_UNDEFINED",
}

export enum SolMerkleTreeErrorCode {
  MERKLE_TREE_UNDEFINED = "MERKLE_TREE_UNDEFINED",
}

export enum TransactionParametersErrorCode {
  NO_VERIFIER_PROVIDED = "NO_VERIFIER_PROVIDED",
  NO_POSEIDON_HASHER_PROVIDED = "NO_POSEIDON_HASHER_PROVIDED",
  NO_ACTION_PROVIDED = "NO_ACTION_PROVIDED",
  PUBLIC_AMOUNT_NEGATIVE = "PUBLIC_AMOUNT_NEGATIVE",
  SOL_RECIPIENT_DEFINED = "SOL_RECIPIENT_DEFINED",
  SPL_RECIPIENT_DEFINED = "SPL_RECIPIENT_DEFINED",
  PUBLIC_AMOUNT_NOT_U64 = "PUBLIC_AMOUNT_NOT_U64",
  RELAYER_DEFINED = "RELAYER_DEFINED",
  INVALID_PUBLIC_AMOUNT = "INVALID_PUBLIC_AMOUNT",
  SOL_SENDER_DEFINED = "SOL_SENDER_DEFINED",
  SPL_SENDER_DEFINED = "SPL_SENDER_DEFINED",
  PUBLIC_AMOUNT_SPL_NOT_ZERO = "PUBLIC_AMOUNT_SPL_NOT_ZERO",
  PUBLIC_AMOUNT_SOL_NOT_ZERO = "PUBLIC_AMOUNT_SOL_NOT_ZERO",
  LOOK_UP_TABLE_UNDEFINED = "LOOK_UP_TABLE_UNDEFINED",
}

export enum TransactionErrorCode {
  PROVIDER_UNDEFINED = "PROVIDER_UNDEFINED",
  ROOT_INDEX_NOT_FETCHED = "ROOT_INDEX_NOT_FETCHED",
  REMAINING_ACCOUNTS_NOT_CREATED = "REMAINING_ACCOUNTS_NOT_CREATED",
  TRANSACTION_INPUTS_UNDEFINED = "TRANSACTION_INPUTS_UNDEFINED",
  WALLET_RELAYER_INCONSISTENT = "WALLET_RELAYER_INCONSISTENT",
  TX_PARAMETERS_UNDEFINED = "TX_PARAMETERS_UNDEFINED",
  APP_PARAMETERS_UNDEFINED = "APP_PARAMETERS_UNDEFINED",
  RELAYER_UNDEFINED = "TransactionParameters.relayer is undefined",
  WALLET_UNDEFINED = "WALLET_UNDEFINED",
  NO_UTXOS_PROVIDED = "NO_UTXOS_PROVIDED",
  EXCEEDED_MAX_ASSETS = "EXCEEDED_MAX_ASSETS",
  VERIFIER_PROGRAM_UNDEFINED = "VERIFIER_PROGRAM_UNDEFINED",
  SPL_RECIPIENT_UNDEFINED = "SPL_RECIPIENT_UNDEFINED",
  SOL_RECIPIENT_UNDEFINED = "SOL_RECIPIENT_UNDEFINED",
  SPL_SENDER_UNDEFINED = "SPL_SENDER_UNDEFINED",
  SOL_SENDER_UNDEFINED = "SOL_SENDER_UNDEFINED",
  ASSET_PUBKEYS_UNDEFINED = "ASSET_PUBKEYS_UNDEFINED",
  ACTION_IS_NO_WITHDRAWAL = "ACTION_IS_NO_WITHDRAWAL",
  ACTION_IS_NO_DEPOSIT = "ACTION_IS_NO_DEPOSIT",
  INPUT_UTXOS_UNDEFINED = "INPUT_UTXOS_UNDEFINED",
  OUTPUT_UTXOS_UNDEFINED = "OUTPUT_UTXOS_UNDEFINED",
  GET_MINT_FAILED = "GET_MINT_FAILED",
  VERIFIER_UNDEFINED = "VERIFIER_UNDEFINED",
  PROOF_INPUT_UNDEFINED = "PROOF_INPUT_UNDEFINED",
  NO_PARAMETERS_PROVIDED = "NO_PARAMETERS_PROVIDED",
  ROOT_NOT_FOUND = "ROOT_NOT_FOUND",
  VERIFIER_CONFIG_UNDEFINED = "VERIFIER_CONFIG_UNDEFINED",
  RELAYER_FEE_UNDEFINED = "RELAYER_FEE_UNDEFINED",
  ENCRYPTING_UTXOS_FAILED = "ENCRYPTING_UTXOS_FAILED",
  GET_INSTRUCTIONS_FAILED = "GET_INSTRUCTIONS_FAILED",
  SEND_TRANSACTION_FAILED = "SEND_TRANSACTION_FAILED",
  PUBLIC_INPUTS_UNDEFINED = "PUBLIC_INPUTS_UNDEFINED",
  MERKLE_TREE_PROGRAM_UNDEFINED = "MERKLE_TREE_PROGRAM_UNDEFINED",
  INPUT_UTXO_NOT_INSERTED_IN_MERKLE_TREE = "INPUT_UTXO_NOT_INSERTED_IN_MERKLE_TREE",
  INVALID_PROOF = "INVALID_PROOF",
  POSEIDON_HASHER_UNDEFINED = "POSEIDON_HASHER_UNDEFINED",
}

export class MetaError extends Error {
  code: string;
  codeMessage?: string;
  functionName: string;

  constructor(code: string, functionName: string, codeMessage?: string) {
    super(`${code}: ${codeMessage}`);

    this.codeMessage = codeMessage;
    this.code = code;
    this.functionName = functionName;
  }
}

/**
 * @description Thrown when something fails in the Transaction class.
 **/
export class TransactionError extends MetaError {}

export class TransactioParametersError extends MetaError {}

/**
 * @description Thrown when something fails in the Utxo class.
 **/
export class UtxoError extends MetaError {}

export class VerifierError extends MetaError {}

export class AccountError extends MetaError {}

export class RelayerError extends MetaError {}
