//! Minimal test program for #[light_account(init, mint, ...)] macro validation.
//!
//! This program tests ONLY the mint creation macro in isolation,
//! ensuring the simplest mint-only program compiles and works correctly.

#![allow(deprecated)]

use anchor_lang::prelude::*;
use light_account::{
    derive_light_cpi_signer, light_program, CpiSigner, CreateAccountsProof, LightAccounts,
};

declare_id!("Mint111111111111111111111111111111111111111");

pub const LIGHT_CPI_SIGNER: CpiSigner =
    derive_light_cpi_signer!("Mint111111111111111111111111111111111111111");

pub const MINT_SIGNER_SEED: &[u8] = b"mint_signer";

#[derive(AnchorSerialize, AnchorDeserialize, Clone)]
pub struct CreateMintParams {
    pub create_accounts_proof: CreateAccountsProof,
    pub mint_signer_bump: u8,
}

/// Minimal accounts struct for testing single mint creation.
#[derive(Accounts, LightAccounts)]
#[instruction(params: CreateMintParams)]
pub struct CreateMint<'info> {
    #[account(mut)]
    pub fee_payer: Signer<'info>,

    pub authority: Signer<'info>,

    /// CHECK: PDA derived from authority
    #[account(
        seeds = [MINT_SIGNER_SEED, authority.key().as_ref()],
        bump,
    )]
    pub mint_signer: UncheckedAccount<'info>,

    /// CHECK: Initialized by light_mint CPI
    #[account(mut)]
    #[light_account(init,
        mint::signer = mint_signer,
        mint::authority = fee_payer,
        mint::decimals = 9,
        mint::seeds = &[MINT_SIGNER_SEED, self.authority.to_account_info().key.as_ref()],
        mint::bump = params.mint_signer_bump
    )]
    pub mint: UncheckedAccount<'info>,

    /// CHECK: Compression config
    pub compression_config: AccountInfo<'info>,

    /// CHECK: CToken config
    pub light_token_config: AccountInfo<'info>,

    /// CHECK: CToken rent sponsor
    #[account(mut)]
    pub light_token_rent_sponsor: AccountInfo<'info>,

    /// CHECK: CToken program
    pub light_token_program: AccountInfo<'info>,

    /// CHECK: CToken CPI authority
    pub light_token_cpi_authority: AccountInfo<'info>,

    pub system_program: Program<'info, System>,
}

#[light_program]
#[program]
pub mod single_mint_test {
    use super::*;

    /// Create a single mint.
    /// The mint account is created by the LightFinalize trait implementation
    /// generated by the #[light_account(init, mint, ...)] macro.
    #[allow(unused_variables)]
    pub fn create_mint<'info>(
        ctx: Context<'_, '_, '_, 'info, CreateMint<'info>>,
        params: CreateMintParams,
    ) -> Result<()> {
        // Mint creation is handled by the macro-generated LightFinalize implementation.
        // Nothing to do here.
        Ok(())
    }
}
