//! Minimal test program for #[light_account(init, associated_token, ...)] macro validation.
//!
//! This program tests ONLY the ATA creation macro in isolation,
//! ensuring the simplest ATA-only program compiles and works correctly.

#![allow(deprecated)]

use anchor_lang::prelude::*;
use light_compressible::CreateAccountsProof;
use light_sdk::derive_light_cpi_signer;
use light_sdk_macros::{light_program, LightAccounts};
use light_sdk_types::{CpiSigner, LIGHT_TOKEN_PROGRAM_ID};
use light_token::instruction::{COMPRESSIBLE_CONFIG_V1, RENT_SPONSOR as LIGHT_TOKEN_RENT_SPONSOR};

declare_id!("AtaT111111111111111111111111111111111111111");

pub const LIGHT_CPI_SIGNER: CpiSigner =
    derive_light_cpi_signer!("AtaT111111111111111111111111111111111111111");

#[derive(AnchorSerialize, AnchorDeserialize, Clone)]
pub struct CreateAtaParams {
    pub create_accounts_proof: CreateAccountsProof,
    /// Bump for the ATA PDA
    pub ata_bump: u8,
}

/// Minimal accounts struct for testing single ATA creation.
#[derive(Accounts, LightAccounts)]
#[instruction(params: CreateAtaParams)]
pub struct CreateAta<'info> {
    #[account(mut)]
    pub fee_payer: Signer<'info>,

    /// CHECK: Token mint for the ATA
    pub ata_mint: AccountInfo<'info>,

    /// CHECK: Owner of the ATA
    pub ata_owner: AccountInfo<'info>,

    /// ATA account - macro should generate creation code.
    #[account(mut)]
    #[light_account(init, associated_token::authority = ata_owner, associated_token::mint = ata_mint, associated_token::bump = params.ata_bump)]
    pub ata: UncheckedAccount<'info>,

    #[account(address = COMPRESSIBLE_CONFIG_V1)]
    pub light_token_compressible_config: AccountInfo<'info>,

    #[account(mut, address = LIGHT_TOKEN_RENT_SPONSOR)]
    pub light_token_rent_sponsor: AccountInfo<'info>,

    /// CHECK: Light Token Program for CPI
    #[account(address = LIGHT_TOKEN_PROGRAM_ID.into())]
    pub light_token_program: AccountInfo<'info>,

    pub system_program: Program<'info, System>,
}

#[light_program]
#[program]
pub mod single_ata_test {
    use super::*;

    /// Create a single ATA.
    /// The ATA is created by the LightFinalize trait implementation
    /// generated by the #[light_account(init, associated_token, ...)] macro.
    #[allow(unused_variables)]
    pub fn create_ata<'info>(
        ctx: Context<'_, '_, '_, 'info, CreateAta<'info>>,
        params: CreateAtaParams,
    ) -> Result<()> {
        // ATA creation is handled by the macro-generated LightFinalize implementation.
        // Nothing to do here.
        Ok(())
    }
}
