# Light Protocol - CLI

default:
    @just --list

# Build JS dependencies first, then CLI
build: build-js-deps
    pnpm build

build-js-deps:
    cd ../js/stateless.js && pnpm build
    cd ../js/compressed-token && pnpm build

test:
    pnpm test
