//! Minimal test program for #[light_account(init, token, ...)] macro validation.
//!
//! This program tests ONLY the token vault creation macro in isolation,
//! ensuring the simplest token-vault-only program compiles and works correctly.

#![allow(deprecated)]

use anchor_lang::prelude::*;
use light_account::{
    derive_light_cpi_signer, CpiSigner, CreateAccountsProof, LIGHT_TOKEN_CONFIG,
    LIGHT_TOKEN_RENT_SPONSOR,
};
use light_sdk_macros::{light_program, LightAccounts};

declare_id!("TknT111111111111111111111111111111111111111");

pub const LIGHT_CPI_SIGNER: CpiSigner =
    derive_light_cpi_signer!("TknT111111111111111111111111111111111111111");

/// Seed for the vault authority PDA
pub const VAULT_AUTH_SEED: &[u8] = b"vault_auth";
/// Seed for the vault token account PDA
pub const VAULT_SEED: &[u8] = b"vault";

#[derive(AnchorSerialize, AnchorDeserialize, Clone)]
pub struct CreateTokenVaultParams {
    pub create_accounts_proof: CreateAccountsProof,
    /// Bump for the vault PDA (needed for invoke_signed)
    pub vault_bump: u8,
}

/// Minimal accounts struct for testing single token vault creation.
#[derive(Accounts, LightAccounts)]
#[instruction(params: CreateTokenVaultParams)]
pub struct CreateTokenVault<'info> {
    #[account(mut)]
    pub fee_payer: Signer<'info>,

    /// CHECK: Token mint
    pub mint: AccountInfo<'info>,

    #[account(
        seeds = [VAULT_AUTH_SEED],
        bump,
    )]
    pub vault_authority: UncheckedAccount<'info>,

    /// Token vault account - macro should generate creation code.
    /// The `seeds` must match the account's PDA seeds for invoke_signed.
    #[account(
        mut,
        seeds = [VAULT_SEED, mint.key().as_ref()],
        bump,
    )]
    #[light_account(init, token::seeds = [VAULT_SEED, self.mint.key()], token::mint = mint, token::owner = vault_authority, token::owner_seeds = [VAULT_AUTH_SEED])]
    pub vault: UncheckedAccount<'info>,

    #[account(address = LIGHT_TOKEN_CONFIG)]
    pub light_token_config: AccountInfo<'info>,

    #[account(mut, address = LIGHT_TOKEN_RENT_SPONSOR)]
    pub light_token_rent_sponsor: AccountInfo<'info>,

    /// CHECK: Light token CPI authority (required for token account creation)
    pub light_token_cpi_authority: AccountInfo<'info>,

    /// CHECK: Light token program for CPI
    pub light_token_program: AccountInfo<'info>,

    pub system_program: Program<'info, System>,
}

#[light_program]
#[program]
pub mod single_token_test {
    use super::*;

    /// Create a single token vault.
    /// The token vault is created by the LightFinalize trait implementation
    /// generated by the #[light_account(init, token, ...)] macro.
    #[allow(unused_variables)]
    pub fn create_token_vault<'info>(
        ctx: Context<'_, '_, '_, 'info, CreateTokenVault<'info>>,
        params: CreateTokenVaultParams,
    ) -> Result<()> {
        // Token vault creation is handled by the macro-generated LightFinalize implementation.
        // Nothing to do here.
        Ok(())
    }
}
