//! Traits for decompression variant construction and Light Protocol implementation.
//!
//! This module contains traits for typed compressed account handling:
//! - Base traits (`IntoVariant`) - always available
//! - Variant traits (`LightAccountVariantTrait`, `PackedLightAccountVariantTrait`) - always available
//! - Token seed traits (`UnpackedTokenSeeds`, `PackedTokenSeeds`) - behind `token` feature

use alloc::vec::Vec;

use light_account_checks::AccountInfoTrait;

use crate::{
    error::LightSdkTypesError, interface::account::light_account::AccountType, AnchorDeserialize,
    AnchorSerialize,
};

// --- Base trait (always available) ---

/// Trait for seeds that can construct a compressed account variant.
///
/// Implemented by generated `XxxSeeds` structs (e.g., `UserRecordSeeds`).
/// The macro generates impls that deserialize account data and verify seeds match.
pub trait IntoVariant<V> {
    /// Construct variant from compressed account data bytes and these seeds.
    fn into_variant(self, data: &[u8]) -> Result<V, LightSdkTypesError>;
}

// --- Variant traits ---

/// Trait for unpacked compressed account variants with seeds.
///
/// Implementations are generated by the `#[light_program]` macro for each
/// account type marked with `#[light_account(init)]`.
///
/// # Type Parameters
/// * `SEED_COUNT` - Number of seeds including bump for CPI signing
pub trait LightAccountVariantTrait<const SEED_COUNT: usize>:
    Sized + Clone + AnchorSerialize + AnchorDeserialize
{
    /// The program ID that owns accounts of this variant type.
    const PROGRAM_ID: [u8; 32];

    /// The seeds struct type containing seed values.
    type Seeds;

    /// The account data type.
    type Data;

    /// The packed variant type for efficient serialization.
    type Packed: PackedLightAccountVariantTrait<SEED_COUNT, Unpacked = Self>;

    /// Get a reference to the account data.
    fn data(&self) -> &Self::Data;

    /// Get seed values as owned byte vectors for PDA derivation.
    fn seed_vec(&self) -> Vec<Vec<u8>>;

    /// Get seed references with bump for CPI signing.
    /// Returns a fixed-size array that can be passed to invoke_signed.
    fn seed_refs_with_bump<'a>(&'a self, bump_storage: &'a [u8; 1]) -> [&'a [u8]; SEED_COUNT];

    /// Derive the PDA address and bump seed using PROGRAM_ID.
    fn derive_pda<AI: AccountInfoTrait>(&self) -> ([u8; 32], u8) {
        let seeds = self.seed_vec();
        let seed_slices: Vec<&[u8]> = seeds.iter().map(|s| s.as_slice()).collect();
        AI::find_program_address(&seed_slices, &Self::PROGRAM_ID)
    }
}

/// Trait for packed compressed account variants.
///
/// Packed variants use u8 indices instead of 32-byte Pubkeys for efficient
/// serialization. They can be unpacked back to full variants using account info.
#[allow(clippy::wrong_self_convention)]
pub trait PackedLightAccountVariantTrait<const SEED_COUNT: usize>:
    Sized + Clone + AnchorSerialize + AnchorDeserialize
{
    /// The unpacked variant type with full Pubkey values.
    type Unpacked: LightAccountVariantTrait<SEED_COUNT>;

    /// The account type (Pda, Token, Ata, etc.) for dispatch.
    const ACCOUNT_TYPE: AccountType;

    /// Get the PDA bump seed.
    fn bump(&self) -> u8;

    /// Unpack this variant by resolving u8 indices to Pubkeys.
    fn unpack<AI: AccountInfoTrait>(
        &self,
        accounts: &[AI],
    ) -> Result<Self::Unpacked, LightSdkTypesError>;

    /// Get seed references with bump for CPI signing.
    /// Resolves u8 indices to pubkey refs from accounts slice.
    fn seed_refs_with_bump<'a, AI: AccountInfoTrait>(
        &'a self,
        accounts: &'a [AI],
        bump_storage: &'a [u8; 1],
    ) -> Result<[&'a [u8]; SEED_COUNT], LightSdkTypesError>;

    /// Extract token data for compressed token CPI.
    /// Only meaningful for token account variants; PDA variants return an error.
    #[cfg(feature = "token")]
    fn into_in_token_data(
        &self,
        _tree_info: &crate::instruction::PackedStateTreeInfo,
        _output_queue_index: u8,
    ) -> Result<
        light_token_interface::instructions::transfer2::MultiInputTokenDataWithContext,
        LightSdkTypesError,
    > {
        Err(LightSdkTypesError::InvalidInstructionData)
    }

    /// Extract TLV extension data for compressed token CPI.
    /// Only meaningful for token account variants; PDA variants return `None`.
    #[cfg(feature = "token")]
    fn into_in_tlv(
        &self,
    ) -> Result<
        Option<Vec<light_token_interface::instructions::extensions::ExtensionInstructionData>>,
        LightSdkTypesError,
    > {
        Ok(None)
    }

    /// Derive the owner pubkey from constant owner_seeds and program ID.
    /// Only meaningful for token account variants; PDA variants return default.
    #[cfg(feature = "token")]
    fn derive_owner(&self) -> [u8; 32] {
        [0u8; 32]
    }
}

// --- Token seed traits (behind `token` feature) ---

#[cfg(feature = "token")]
mod token_traits {
    use alloc::vec::Vec;

    use light_account_checks::AccountInfoTrait;

    use crate::{error::LightSdkTypesError, AnchorDeserialize, AnchorSerialize};

    /// Trait for unpacked token seed structs.
    ///
    /// Generated by the `#[light_program]` macro on per-variant seed structs
    /// (e.g., `TokenVaultSeeds`). Provides seed-specific behavior for the blanket
    /// `LightAccountVariantTrait` impl on `TokenDataWithSeeds<S>`.
    pub trait UnpackedTokenSeeds<const N: usize>:
        Clone + core::fmt::Debug + AnchorSerialize + AnchorDeserialize
    {
        /// The packed seeds type.
        type Packed: PackedTokenSeeds<N, Unpacked = Self>;

        const PROGRAM_ID: [u8; 32];
        fn seed_vec(&self) -> Vec<Vec<u8>>;
        fn seed_refs_with_bump<'a>(&'a self, bump_storage: &'a [u8; 1]) -> [&'a [u8]; N];
    }

    /// Trait for packed token seed structs.
    ///
    /// Generated by the `#[light_program]` macro on per-variant packed seed structs
    /// (e.g., `PackedTokenVaultSeeds`). Provides seed-specific behavior for the blanket
    /// `PackedLightAccountVariantTrait` impl on `TokenDataWithPackedSeeds<S>`.
    ///
    /// Note: `Unpack<AI>` cannot be a supertrait because `AI` is not available in
    /// the trait definition. Instead, generic unpack/seed methods are defined here directly.
    pub trait PackedTokenSeeds<const N: usize>:
        Clone + core::fmt::Debug + AnchorSerialize + AnchorDeserialize
    {
        type Unpacked: UnpackedTokenSeeds<N>;

        fn bump(&self) -> u8;

        /// Unpack seeds by resolving u8 indices to pubkeys from accounts slice.
        fn unpack_seeds<AI: AccountInfoTrait>(
            &self,
            accounts: &[AI],
        ) -> Result<Self::Unpacked, LightSdkTypesError>;

        /// Get seed references with bump for CPI signing.
        fn seed_refs_with_bump<'a, AI: AccountInfoTrait>(
            &'a self,
            accounts: &'a [AI],
            bump_storage: &'a [u8; 1],
        ) -> Result<[&'a [u8]; N], LightSdkTypesError>;

        /// Derive the owner pubkey from constant owner_seeds and program ID.
        fn derive_owner(&self) -> [u8; 32];
    }
}

#[cfg(feature = "token")]
pub use token_traits::{PackedTokenSeeds, UnpackedTokenSeeds};
