//! LightFinalize and LightPreInit traits for compression operations.
//!
//! These traits are implemented by the `#[derive(LightFinalize)]` macro from light-sdk-macros.
//! They provide hooks for running compression operations at different points in an instruction:
//!
//! - `LightPreInit`: Called at START of instruction - creates mints via CPI context write
//! - `LightFinalize`: Called at END of instruction - compresses PDAs and executes with proof
//!
//! This two-phase design allows mints to be created BEFORE the instruction body runs,
//! so they can be used during the instruction (e.g., for vault creation, minting tokens).

use light_account_checks::AccountInfoTrait;

/// Trait for pre-initialization operations (mint creation).
///
/// This is generated by `#[derive(LightFinalize)]` when `#[light_account(init)]` fields exist.
/// Called at the START of an instruction to write mint creation to CPI context.
///
/// The mints are written to CPI context but NOT executed yet - execution happens
/// in `light_finalize()` at the end, allowing the shared proof to cover both
/// mints and PDAs.
///
/// # Type Parameters
/// * `AI` - AccountInfoTrait implementation (solana or pinocchio)
/// * `P` - The instruction params type (from `#[instruction(params: P)]`)
pub trait LightPreInit<AI: AccountInfoTrait, P> {
    /// Execute pre-initialization operations (mint creation).
    fn light_pre_init(
        &mut self,
        remaining_accounts: &[AI],
        params: &P,
    ) -> Result<bool, crate::error::LightSdkTypesError>;
}

/// Trait for finalizing compression operations on accounts.
///
/// # Type Parameters
/// * `AI` - AccountInfoTrait implementation (solana or pinocchio)
/// * `P` - The instruction params type (from `#[instruction(params: P)]`)
pub trait LightFinalize<AI: AccountInfoTrait, P> {
    /// Execute compression finalization.
    fn light_finalize(
        &mut self,
        remaining_accounts: &[AI],
        params: &P,
        has_pre_init: bool,
    ) -> Result<(), crate::error::LightSdkTypesError>;
}
