#!/usr/bin/env bash
set -euo pipefail

# Create release PR with current changes
# Usage: ./scripts/create-release-pr.sh <program-libs|sdk-libs>

if [ $# -ne 1 ]; then
    echo "Usage: $0 <program-libs|sdk-libs>"
    exit 1
fi

RELEASE_TYPE=$1

if [[ ! "$RELEASE_TYPE" =~ ^(program-libs|sdk-libs)$ ]]; then
    echo "Error: Release type must be 'program-libs' or 'sdk-libs'"
    exit 1
fi

# Check if there are changes
if git diff --quiet; then
    echo "No changes detected. Please bump versions first."
    exit 1
fi

echo "========================================="
echo "Creating $RELEASE_TYPE release PR"
echo "========================================="
echo ""

# Show what changed
echo "Changed files:"
git diff --name-only | grep Cargo.toml || echo "  (no Cargo.toml changes)"
echo ""

# Extract version changes
echo "Version changes:"
git diff | grep -E '^\+version|^-version' | head -20 || echo "  (could not detect)"
echo ""

read -p "Create release PR with these changes? (y/N) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Cancelled."
    exit 1
fi

# Create release branch
BRANCH_NAME="release/${RELEASE_TYPE}"

echo ""
echo "Creating release branch: $BRANCH_NAME"
git checkout -b "$BRANCH_NAME"

# Commit changes
git add -A
git commit -m "chore(${RELEASE_TYPE}): bump versions"

# Push branch
echo "Pushing branch to origin..."
git push -u origin "$BRANCH_NAME"

# Create PR
echo ""
echo "Creating pull request..."
gh pr create \
  --title "chore(${RELEASE_TYPE}): Bump versions" \
  --body "## ${RELEASE_TYPE^} Release

This PR bumps versions for ${RELEASE_TYPE} crates.

### Release Process
1. Versions bumped in Cargo.toml files
2. PR validation (dry-run) will run automatically
3. After merge, GitHub Action will publish each crate individually to crates.io and create releases

---
*Generated by \`scripts/create-release-pr.sh ${RELEASE_TYPE}\`*" \
  --label "release"

echo ""
echo "Pull request created!"
echo ""
echo "Next steps:"
echo "1. Wait for PR checks to pass (dry-run validation)"
echo "2. Review and merge the PR"
echo "3. GitHub Action will automatically publish to crates.io and create releases"
