#!/usr/bin/env bash
set -euo pipefail

# Bump versions for all program-libs crates and create PR
# Usage: ./scripts/release-program-libs.sh [patch|minor|major]
#
# This script:
# 1. Bumps versions in Cargo.toml files
# 2. Creates a branch and commits changes
# 3. Pushes branch and creates PR
# 4. PR triggers GitHub Actions for validation and actual release

PROGRAM_LIBS=(
    "light-account-checks"
    "aligned-sized"
    "light-batched-merkle-tree"
    "light-bloom-filter"
    "light-compressed-account"
    "light-concurrent-merkle-tree"
    "light-hash-set"
    "light-hasher"
    "light-heap"
    "light-indexed-array"
    "light-indexed-merkle-tree"
    "light-macros"
    "light-merkle-tree-metadata"
    "light-verifier"
    "light-zero-copy-derive"
    "light-zero-copy"
)

# Parse arguments
BUMP_LEVEL="${1:-patch}"

# Validate bump level
if [[ "$BUMP_LEVEL" != "patch" && "$BUMP_LEVEL" != "minor" && "$BUMP_LEVEL" != "major" ]]; then
    echo "Error: Invalid bump level '$BUMP_LEVEL'"
    echo "Usage: $0 [patch|minor|major]"
    exit 1
fi

# Build the package arguments
PACKAGE_ARGS=""
for pkg in "${PROGRAM_LIBS[@]}"; do
    PACKAGE_ARGS="$PACKAGE_ARGS -p $pkg"
done

# Create release branch
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
BRANCH_NAME="release/program-libs-${BUMP_LEVEL}-${TIMESTAMP}"

echo "Creating release branch: $BRANCH_NAME"
git checkout -b "$BRANCH_NAME"

echo ""
echo "Bumping versions for ${#PROGRAM_LIBS[@]} program-libs crates ($BUMP_LEVEL)..."
echo "cargo-release will automatically handle dependency ordering and workspace dependencies"
echo ""

# Run cargo-release to bump versions only (no publish, no tag, no push)
cargo release version $BUMP_LEVEL $PACKAGE_ARGS --execute --no-confirm

echo ""
echo "✓ Versions bumped successfully!"
echo ""

# Commit changes
git add -A
git commit -m "chore(program-libs): bump versions ($BUMP_LEVEL)"

# Push branch
echo "Pushing branch to origin..."
git push -u origin "$BRANCH_NAME"

# Create PR
echo ""
echo "Creating pull request..."
gh pr create \
  --title "chore(program-libs): Release $BUMP_LEVEL version bump" \
  --body "## Program Libs Release

This PR bumps versions for all program-libs crates.

**Bump level:** \`$BUMP_LEVEL\`

**Crates included:**
$(printf '- %s\n' "${PROGRAM_LIBS[@]}")

### Release Process
1. ✅ Versions bumped in Cargo.toml files
2. ⏳ PR validation (dry-run) will run automatically
3. ⏳ After merge, GitHub Action will publish to crates.io and create releases

---
*Generated by \`scripts/release-program-libs.sh\`*" \
  --label "release"

echo ""
echo "✓ Pull request created!"
echo ""
echo "Next steps:"
echo "1. Wait for PR checks to pass (dry-run validation)"
echo "2. Review and merge the PR"
echo "3. GitHub Action will automatically publish to crates.io and create releases"
