/*
 * photon-indexer
 *
 * Solana indexer for general compression
 *
 * The version of the OpenAPI document: 0.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GetQueueElementsV2PostRequestParams {
    /// The merkle tree public key
    pub tree: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_queue: Option<models::QueueRequest>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub input_queue: Option<models::QueueRequest>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub address_queue: Option<models::QueueRequest>,
}

impl GetQueueElementsV2PostRequestParams {
    pub fn new(tree: String) -> GetQueueElementsV2PostRequestParams {
        GetQueueElementsV2PostRequestParams {
            tree,
            output_queue: None,
            input_queue: None,
            address_queue: None,
        }
    }
}
