/*
 * photon-indexer
 *
 * Solana indexer for general compression
 *
 * The version of the OpenAPI document: 0.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// GetCompressedMintsByAuthorityPostRequestParams : Request for compressed mints by authority
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCompressedMintsByAuthorityPostRequestParams {
    /// A Solana public key represented as a base58 string.
    #[serde(rename = "authority")]
    pub authority: String,
    /// Type of authority to filter by: mintAuthority, freezeAuthority, or both (default).
    #[serde(
        rename = "authorityType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub authority_type: Option<AuthorityType>,
    /// A base 58 encoded string.
    #[serde(rename = "cursor", default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    #[serde(rename = "limit", default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<u16>,
}

impl GetCompressedMintsByAuthorityPostRequestParams {
    pub fn new(authority: String) -> GetCompressedMintsByAuthorityPostRequestParams {
        GetCompressedMintsByAuthorityPostRequestParams {
            authority,
            authority_type: None,
            cursor: None,
            limit: None,
        }
    }
}

/// Type of authority to filter by.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AuthorityType {
    #[serde(rename = "mintAuthority")]
    MintAuthority,
    #[serde(rename = "freezeAuthority")]
    FreezeAuthority,
    #[serde(rename = "both")]
    Both,
}

impl Default for AuthorityType {
    fn default() -> AuthorityType {
        Self::Both
    }
}
