/*
 * photon-indexer
 *
 * Solana indexer for general compression
 *
 * The version of the OpenAPI document: 0.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetBatchAddressUpdateInfoPostRequestParams {
    #[serde(rename = "batchSize")]
    pub batch_size: u16,
    /// A 32-byte hash represented as a base58 string.
    #[serde(rename = "tree")]
    pub tree: String,
}

impl GetBatchAddressUpdateInfoPostRequestParams {
    pub fn new(batch_size: u16, tree: String) -> GetBatchAddressUpdateInfoPostRequestParams {
        GetBatchAddressUpdateInfoPostRequestParams { batch_size, tree }
    }
}
