/*
 * photon-indexer
 *
 * Solana indexer for general compression
 *
 * The version of the OpenAPI document: 0.50.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetQueueElementsPostRequestParams {
    /// A 32-byte hash represented as a base58 string.
    #[serde(rename = "merkleTree")]
    pub merkle_tree: String,
    #[serde(rename = "startOffset")]
    pub start_offset: u64,
    #[serde(rename = "endOffset")]
    pub end_offset: u64,
}

impl GetQueueElementsPostRequestParams {
    pub fn new(merkle_tree: String, start_offset: u64, end_offset: u64) -> GetQueueElementsPostRequestParams {
        GetQueueElementsPostRequestParams {
            merkle_tree,
            start_offset,
            end_offset,
        }
    }
}

