/*
 * photon-indexer
 *
 * Solana indexer for general compression
 *
 * The version of the OpenAPI document: 0.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetQueueElementsV2PostRequestParams {
    /// The merkle tree public key
    #[serde(rename = "tree")]
    pub tree: String,
    /// Starting index for the output queue
    #[serde(
        rename = "outputQueueStartIndex",
        skip_serializing_if = "Option::is_none"
    )]
    pub output_queue_start_index: Option<u64>,
    /// Limit for the output queue elements
    #[serde(rename = "outputQueueLimit", skip_serializing_if = "Option::is_none")]
    pub output_queue_limit: Option<u16>,
    /// Starting index for the input queue
    #[serde(
        rename = "inputQueueStartIndex",
        skip_serializing_if = "Option::is_none"
    )]
    pub input_queue_start_index: Option<u64>,
    /// Limit for the input queue elements
    #[serde(rename = "inputQueueLimit", skip_serializing_if = "Option::is_none")]
    pub input_queue_limit: Option<u16>,
    /// Starting index for the address queue
    #[serde(
        rename = "addressQueueStartIndex",
        skip_serializing_if = "Option::is_none"
    )]
    pub address_queue_start_index: Option<u64>,
    /// Limit for the address queue elements
    #[serde(rename = "addressQueueLimit", skip_serializing_if = "Option::is_none")]
    pub address_queue_limit: Option<u16>,
}

impl GetQueueElementsV2PostRequestParams {
    pub fn new(tree: String) -> GetQueueElementsV2PostRequestParams {
        GetQueueElementsV2PostRequestParams {
            tree,
            output_queue_start_index: None,
            output_queue_limit: None,
            input_queue_start_index: None,
            input_queue_limit: None,
            address_queue_start_index: None,
            address_queue_limit: None,
        }
    }
}
