/*
 * photon-indexer
 *
 * Solana indexer for general compression
 *
 * The version of the OpenAPI document: 0.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// GetCompressedMintPostRequestParams : Request for compressed mint data
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCompressedMintPostRequestParams {
    /// A Solana public key represented as a base58 string (compressed address).
    #[serde(rename = "address", default, skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    /// A Solana public key represented as a base58 string (mint PDA).
    #[serde(rename = "mintPda", default, skip_serializing_if = "Option::is_none")]
    pub mint_pda: Option<String>,
}

impl GetCompressedMintPostRequestParams {
    /// Request for compressed mint data
    pub fn new() -> GetCompressedMintPostRequestParams {
        GetCompressedMintPostRequestParams {
            address: None,
            mint_pda: None,
        }
    }
}
