/*
 * photon-indexer
 *
 * Solana indexer for general compression
 *
 * The version of the OpenAPI document: 0.50.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetLeafInfoPostRequestParams {
    /// A 32-byte hash represented as a base58 string.
    #[serde(rename = "merkleTree")]
    pub merkle_tree: String,
    #[serde(rename = "zkpBatchSize")]
    pub zkp_batch_size: u64,
}

impl GetLeafInfoPostRequestParams {
    pub fn new(merkle_tree: String, zkp_batch_size: u64) -> GetLeafInfoPostRequestParams {
        GetLeafInfoPostRequestParams {
            merkle_tree,
            zkp_batch_size,
        }
    }
}

