/*
 * photon-indexer
 *
 * Solana indexer for general compression
 *
 * The version of the OpenAPI document: 0.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountWithContext {
    #[serde(rename = "account")]
    pub account: Box<models::Account>,
    #[serde(rename = "context")]
    pub context: Box<models::AccountContext>,
}

impl AccountWithContext {
    pub fn new(account: models::Account, context: models::AccountContext) -> AccountWithContext {
        AccountWithContext {
            account: Box::new(account),
            context: Box::new(context),
        }
    }
}
