/*
 * photon-indexer
 *
 * Solana indexer for general compression
 *
 * The version of the OpenAPI document: 0.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountWithOptionalTokenDataV2 {
    #[serde(rename = "account")]
    pub account: Box<models::AccountV2>,
    #[serde(rename = "optionalTokenData", skip_serializing_if = "Option::is_none")]
    pub optional_token_data: Option<Box<models::TokenData>>,
}

impl AccountWithOptionalTokenDataV2 {
    pub fn new(account: models::AccountV2) -> AccountWithOptionalTokenDataV2 {
        AccountWithOptionalTokenDataV2 {
            account: Box::new(account),
            optional_token_data: None,
        }
    }
}
