/*
 * photon-indexer
 *
 * Solana indexer for general compression
 *
 * The version of the OpenAPI document: 0.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddressWithTree {
    /// A Solana public key represented as a base58 string.
    #[serde(rename = "address")]
    pub address: String,
    /// A Solana public key represented as a base58 string.
    #[serde(rename = "tree")]
    pub tree: String,
}

impl AddressWithTree {
    pub fn new(address: String, tree: String) -> AddressWithTree {
        AddressWithTree { address, tree }
    }
}
