/*
 * photon-indexer
 *
 * Solana indexer for general compression
 *
 * The version of the OpenAPI document: 0.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[allow(clippy::too_many_arguments)]
pub struct AddressQueueDataV2 {
    pub addresses: Vec<String>,
    pub queue_indices: Vec<u64>,
    /// Deduplicated tree nodes for address tree non-inclusion proofs
    pub nodes: Vec<models::Node>,
    pub low_element_indices: Vec<u64>,
    pub low_element_values: Vec<String>,
    pub low_element_next_indices: Vec<u64>,
    pub low_element_next_values: Vec<String>,
    pub leaves_hash_chains: Vec<String>,
    pub initial_root: String,
    pub start_index: u64,
    pub subtrees: Vec<String>,
    pub root_seq: u64,
}

impl AddressQueueDataV2 {
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        addresses: Vec<String>,
        queue_indices: Vec<u64>,
        nodes: Vec<models::Node>,
        low_element_indices: Vec<u64>,
        low_element_values: Vec<String>,
        low_element_next_indices: Vec<u64>,
        low_element_next_values: Vec<String>,
        leaves_hash_chains: Vec<String>,
        initial_root: String,
        start_index: u64,
        subtrees: Vec<String>,
        root_seq: u64,
    ) -> AddressQueueDataV2 {
        AddressQueueDataV2 {
            addresses,
            queue_indices,
            nodes,
            low_element_indices,
            low_element_values,
            low_element_next_indices,
            low_element_next_values,
            leaves_hash_chains,
            initial_root,
            start_index,
            subtrees,
            root_seq,
        }
    }
}
