/*
 * photon-indexer
 *
 * Solana indexer for general compression
 *
 * The version of the OpenAPI document: 0.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClosedAccount {
    #[serde(rename = "account")]
    pub account: Box<models::AccountV2>,
    /// A 32-byte hash represented as a base58 string.
    #[serde(rename = "nullifier")]
    pub nullifier: String,
    /// A 32-byte hash represented as a base58 string.
    #[serde(rename = "txHash")]
    pub tx_hash: String,
}

impl ClosedAccount {
    pub fn new(account: models::AccountV2, nullifier: String, tx_hash: String) -> ClosedAccount {
        ClosedAccount {
            account: Box::new(account),
            nullifier,
            tx_hash,
        }
    }
}
