/*
 * photon-indexer
 *
 * Solana indexer for general compression
 *
 * The version of the OpenAPI document: 0.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompressedMint {
    #[serde(rename = "account")]
    pub account: Box<models::AccountV2>,
    #[serde(rename = "mintData")]
    pub mint_data: Box<models::MintData>,
}

impl CompressedMint {
    pub fn new(account: models::AccountV2, mint_data: models::MintData) -> CompressedMint {
        CompressedMint {
            account: Box::new(account),
            mint_data: Box::new(mint_data),
        }
    }
}
