/*
 * photon-indexer
 *
 * Solana indexer for general compression
 *
 * The version of the OpenAPI document: 0.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InputQueueDataV2 {
    #[serde(rename = "leafIndices")]
    pub leaf_indices: Vec<u64>,
    #[serde(rename = "accountHashes")]
    pub account_hashes: Vec<String>,
    #[serde(rename = "leaves")]
    pub leaves: Vec<String>,
    #[serde(rename = "txHashes")]
    pub tx_hashes: Vec<String>,
    #[serde(rename = "nodes")]
    pub nodes: Vec<u64>,
    #[serde(rename = "nodeHashes")]
    pub node_hashes: Vec<String>,
    #[serde(rename = "initialRoot")]
    pub initial_root: String,
    #[serde(rename = "firstQueueIndex")]
    pub first_queue_index: u64,
}

impl InputQueueDataV2 {
    pub fn new(
        leaf_indices: Vec<u64>,
        account_hashes: Vec<String>,
        current_leaves: Vec<String>,
        tx_hashes: Vec<String>,
        nodes: Vec<u64>,
        node_hashes: Vec<String>,
        initial_root: String,
        first_queue_index: u64,
    ) -> InputQueueDataV2 {
        InputQueueDataV2 {
            leaf_indices,
            account_hashes,
            leaves: current_leaves,
            tx_hashes,
            nodes,
            node_hashes,
            initial_root,
            first_queue_index,
        }
    }
}
