/*
 * photon-indexer
 *
 * Solana indexer for general compression
 *
 * The version of the OpenAPI document: 0.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Memcmp {
    /// A base 58 encoded string.
    #[serde(rename = "bytes")]
    pub bytes: String,
    #[serde(rename = "offset")]
    pub offset: u32,
}

impl Memcmp {
    pub fn new(bytes: String, offset: u32) -> Memcmp {
        Memcmp { bytes, offset }
    }
}
