/*
 * photon-indexer
 *
 * Solana indexer for general compression
 *
 * The version of the OpenAPI document: 0.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// MintData : Compressed mint account data

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MintData {
    /// A Solana public key represented as a base58 string.
    #[serde(rename = "mintPda")]
    pub mint_pda: String,
    /// A Solana public key represented as a base58 string.
    #[serde(rename = "mintSigner")]
    pub mint_signer: String,
    /// A Solana public key represented as a base58 string.
    #[serde(rename = "mintAuthority", skip_serializing_if = "Option::is_none")]
    pub mint_authority: Option<String>,
    /// A Solana public key represented as a base58 string.
    #[serde(rename = "freezeAuthority", skip_serializing_if = "Option::is_none")]
    pub freeze_authority: Option<String>,
    #[serde(rename = "supply")]
    pub supply: u64,
    #[serde(rename = "decimals")]
    pub decimals: u8,
    #[serde(rename = "version")]
    pub version: u8,
    #[serde(rename = "mintDecompressed")]
    pub mint_decompressed: bool,
    /// A base 64 encoded string.
    #[serde(rename = "extensions", skip_serializing_if = "Option::is_none")]
    pub extensions: Option<String>,
}

impl MintData {
    pub fn new(
        mint_pda: String,
        mint_signer: String,
        supply: u64,
        decimals: u8,
        version: u8,
        mint_decompressed: bool,
    ) -> MintData {
        MintData {
            mint_pda,
            mint_signer,
            mint_authority: None,
            freeze_authority: None,
            supply,
            decimals,
            version,
            mint_decompressed,
            extensions: None,
        }
    }
}
