/*
 * photon-indexer
 *
 * Solana indexer for general compression
 *
 * The version of the OpenAPI document: 0.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// A tree node with its encoded index and hash
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Node {
    /// Encoded node index: (level << 56) | position
    pub index: u64,
    pub hash: String,
}

impl Node {
    pub fn new(index: u64, hash: String) -> Node {
        Node { index, hash }
    }
}
