/*
 * photon-indexer
 *
 * Solana indexer for general compression
 *
 * The version of the OpenAPI document: 0.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OutputQueueDataV2 {
    #[serde(rename = "leafIndices")]
    pub leaf_indices: Vec<u64>,
    #[serde(rename = "accountHashes")]
    pub account_hashes: Vec<String>,
    #[serde(rename = "leaves")]
    pub leaves: Vec<String>,
    #[serde(rename = "nodes")]
    pub nodes: Vec<u64>,
    #[serde(rename = "nodeHashes")]
    pub node_hashes: Vec<String>,
    #[serde(rename = "initialRoot")]
    pub initial_root: String,
    #[serde(rename = "firstQueueIndex")]
    pub first_queue_index: u64,
}

impl OutputQueueDataV2 {
    pub fn new(
        leaf_indices: Vec<u64>,
        account_hashes: Vec<String>,
        old_leaves: Vec<String>,
        nodes: Vec<u64>,
        node_hashes: Vec<String>,
        initial_root: String,
        first_queue_index: u64,
    ) -> OutputQueueDataV2 {
        OutputQueueDataV2 {
            leaf_indices,
            account_hashes,
            leaves: old_leaves,
            nodes,
            node_hashes,
            initial_root,
            first_queue_index,
        }
    }
}