/*
 * photon-indexer
 *
 * Solana indexer for general compression
 *
 * The version of the OpenAPI document: 0.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaginatedAccountListWithContext {
    /// A 32-byte hash represented as a base58 string.
    #[serde(rename = "cursor", skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    #[serde(rename = "items")]
    pub items: Vec<models::AccountWithContext>,
}

impl PaginatedAccountListWithContext {
    pub fn new(items: Vec<models::AccountWithContext>) -> PaginatedAccountListWithContext {
        PaginatedAccountListWithContext {
            cursor: None,
            items,
        }
    }
}
