/*
 * photon-indexer
 *
 * Solana indexer for general compression
 *
 * The version of the OpenAPI document: 0.50.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueueElement {
    #[serde(rename = "hash")]
    pub hash: Vec<u8>,
    #[serde(rename = "leaf_index")]
    pub leaf_index: u64,
}

impl QueueElement {
    pub fn new(hash: Vec<u8>, leaf_index: u64) -> QueueElement {
        QueueElement {
            hash,
            leaf_index,
        }
    }
}

