/*
 * photon-indexer
 *
 * Solana indexer for general compression
 *
 * The version of the OpenAPI document: 0.50.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RootIndex {
    #[serde(rename = "inTree")]
    pub in_tree: bool,
    #[serde(rename = "rootIndex")]
    pub root_index: u16,
}

impl RootIndex {
    pub fn new(in_tree: bool, root_index: u16) -> RootIndex {
        RootIndex {
            in_tree,
            root_index,
        }
    }
}

