/*
 * photon-indexer
 *
 * Solana indexer for general compression
 *
 * The version of the OpenAPI document: 0.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignatureInfo {
    /// An Unix timestamp (seconds)
    #[serde(
        rename = "blockTime",
        deserialize_with = "crate::string_u64::direct::deserialize",
        serialize_with = "crate::string_u64::direct::serialize"
    )]
    pub block_time: u64,
    /// A Solana transaction signature.
    #[serde(rename = "signature")]
    pub signature: String,
    #[serde(
        rename = "slot",
        deserialize_with = "crate::string_u64::direct::deserialize",
        serialize_with = "crate::string_u64::direct::serialize"
    )]
    pub slot: u64,
}

impl SignatureInfo {
    pub fn new(block_time: u64, signature: String, slot: u64) -> SignatureInfo {
        SignatureInfo {
            block_time,
            signature,
            slot,
        }
    }
}
