/*
 * photon-indexer
 *
 * Solana indexer for general compression
 *
 * The version of the OpenAPI document: 0.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenAccountListV2 {
    /// A base 58 encoded string.
    #[serde(rename = "cursor", skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    #[serde(rename = "items")]
    pub items: Vec<models::TokenAccountV2>,
}

impl TokenAccountListV2 {
    pub fn new(items: Vec<models::TokenAccountV2>) -> TokenAccountListV2 {
        TokenAccountListV2 {
            cursor: None,
            items,
        }
    }
}
