/*
 * photon-indexer
 *
 * Solana indexer for general compression
 *
 * The version of the OpenAPI document: 0.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenAccountV2 {
    #[serde(rename = "account")]
    pub account: Box<models::AccountV2>,
    #[serde(rename = "tokenData")]
    pub token_data: Box<models::TokenData>,
}

impl TokenAccountV2 {
    pub fn new(account: models::AccountV2, token_data: models::TokenData) -> TokenAccountV2 {
        TokenAccountV2 {
            account: Box::new(account),
            token_data: Box::new(token_data),
        }
    }
}
