/*
 * photon-indexer
 *
 * Solana indexer for general compression
 *
 * The version of the OpenAPI document: 0.50.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenAccountBalance {
    #[serde(rename = "amount")]
    pub amount: u64,
}

impl TokenAccountBalance {
    pub fn new(amount: u64) -> TokenAccountBalance {
        TokenAccountBalance { amount }
    }
}
