use anchor_lang::prelude::*;

/**
 * This file is auto-generated by the Light cli.
 * DO NOT EDIT MANUALLY.
 * THE FILE WILL BE OVERWRITTEN EVERY TIME THE LIGHT CLI BUILD IS RUN.
 */
#[allow(non_camel_case_types)]
// helper struct to create anchor idl with u256 type
#[account]
#[derive(Debug, Copy, PartialEq)]
pub struct u256 {
    pub x: [u8; 32],
}

pub const NR_CHECKED_INPUTS: usize = 7;

#[allow(non_snake_case)]
#[derive(Debug)]
#[account]
pub struct InstructionDataLightInstructionSecond {
    pub publicPspAddress: [u8; 32],
    pub publicCurrentSlot: [u8; 32],
    pub publicMaxLockTime: [u8; 32],
    pub publicGoverningTokenMint: [u8; 32],
    pub publicVoteUtxoNumber: [u8; 32],
}

#[allow(non_snake_case)]
#[derive(Debug, Copy, PartialEq)]
#[account]
pub struct Utxo {
    pub amounts: [u64; 2],
    pub spl_asset_index: u64,
    pub verifier_address_index: u64,
    pub blinding: u256,
    pub app_data_hash: u256,
    pub account_shielded_public_key: u256,
    pub account_encryption_public_key: [u8; 32],
    pub voteWeight: u256,
    pub startSlot: u256,
    pub releaseSlot: u256,
    pub rate: u256,
    pub voteLock: u256,
    pub voteUtxoNumber: u256,
    pub voteUtxoIdNonce: u256,
    pub voteWeightPspAddress: u256,
}

#[allow(non_snake_case)]
#[account]
#[derive(Debug, Copy, PartialEq)]
pub struct UtxoAppData {
    pub voteWeight: u256,
    pub startSlot: u256,
    pub releaseSlot: u256,
    pub rate: u256,
    pub voteLock: u256,
    pub voteUtxoNumber: u256,
    pub voteUtxoIdNonce: u256,
    pub voteWeightPspAddress: u256,
}
