//! Minimal test program for `#[light_account(init, zero_copy)]` validation.
//!
//! This program tests ONLY the compressible PDA creation macro with AccountLoader
//! in isolation, ensuring zero-copy (Pod) accounts compile and work correctly.

#![allow(deprecated)]

use anchor_lang::prelude::*;
use light_account::{
    derive_light_cpi_signer, light_program, CpiSigner, CreateAccountsProof, LightAccounts,
};

pub mod state;

pub use state::*;

declare_id!("ZCpy111111111111111111111111111111111111111");

pub const LIGHT_CPI_SIGNER: CpiSigner =
    derive_light_cpi_signer!("ZCpy111111111111111111111111111111111111111");

pub const RECORD_SEED: &[u8] = b"zero_copy_record";

#[derive(AnchorSerialize, AnchorDeserialize, Clone)]
pub struct CreateRecordParams {
    pub create_accounts_proof: CreateAccountsProof,
    pub owner: Pubkey,
}

/// Accounts struct for creating a zero-copy record.
/// Uses AccountLoader for Pod (zero-copy) account access.
#[derive(Accounts, LightAccounts)]
#[instruction(params: CreateRecordParams)]
pub struct CreateRecord<'info> {
    #[account(mut)]
    pub fee_payer: Signer<'info>,

    /// CHECK: Compression config PDA
    pub compression_config: AccountInfo<'info>,

    /// CHECK: PDA rent sponsor for rent reimbursement
    #[account(mut)]
    pub pda_rent_sponsor: AccountInfo<'info>,

    /// The zero-copy record account.
    /// Uses AccountLoader which requires `#[light_account(init, zero_copy)]`.
    #[account(
        init,
        payer = fee_payer,
        space = 8 + core::mem::size_of::<ZeroCopyRecord>(),
        seeds = [RECORD_SEED, params.owner.as_ref()],
        bump,
    )]
    #[light_account(init, zero_copy)]
    pub record: AccountLoader<'info, ZeroCopyRecord>,

    pub system_program: Program<'info, System>,
}

#[light_program]
#[program]
pub mod single_account_loader_test {
    use super::*;

    /// Create a single compressible zero-copy PDA.
    /// The account is created by Anchor and made compressible by the
    /// LightFinalize trait implementation generated by `#[light_account(init, zero_copy)]`.
    pub fn create_record<'info>(
        ctx: Context<'_, '_, '_, 'info, CreateRecord<'info>>,
        params: CreateRecordParams,
    ) -> Result<()> {
        // Initialize the record data using load_init for zero-copy access
        let mut record = ctx.accounts.record.load_init()?;
        record.owner = params.owner;
        record.counter = 0;
        // compression_info is handled by the macro-generated LightPreInit
        Ok(())
    }
}
