# Light Protocol - Program Libraries

default:
    @just --list

test: test-fast test-slow

test-fast:
    cargo test -p light-macros
    cargo test -p aligned-sized
    cargo test -p light-array-map --all-features
    cargo test -p light-hasher --all-features
    cargo test -p light-compressed-account --all-features
    cargo test -p light-account-checks --all-features
    cargo test -p light-verifier --all-features
    cargo test -p light-merkle-tree-metadata --all-features
    cargo test -p light-zero-copy --features "std, mut, derive"
    cargo test -p light-zero-copy-derive --all-features
    cargo test -p zero-copy-derive-test
    cargo test -p light-hash-set --all-features
    cargo test -p batched-merkle-tree-test -- --skip test_simulate_transactions --skip test_e2e
    cargo test -p light-concurrent-merkle-tree
    cargo test -p light-token-interface --features poseidon
    cargo test -p light-compressible --all-features

test-slow:
    cargo test -p light-bloom-filter --all-features
    cargo test -p light-indexed-merkle-tree --all-features
    cargo test -p batched-merkle-tree-test -- test_e2e

test-simulate:
    cargo test -p light-batched-merkle-tree --features test-only
    RUST_LOG=light_prover_client=debug cargo test -p batched-merkle-tree-test -- test_simulate_transactions
