// Auto-generated by compressible_instructions macro.

use anchor_lang::prelude::*;
use light_sdk::compressible::process_initialize_compression_config_checked;

use crate::instruction_accounts::*;

pub fn initialize_compression_config(
    ctx: Context<InitializeCompressionConfig>,
    compression_delay: u32,
    rent_sponsor: Pubkey,
    address_space: Vec<Pubkey>,
) -> Result<()> {
    process_initialize_compression_config_checked(
        &ctx.accounts.config.to_account_info(),
        &ctx.accounts.authority.to_account_info(),
        &ctx.accounts.program_data.to_account_info(),
        &rent_sponsor,
        address_space,
        compression_delay,
        0, // one global config for now, so bump is 0.
        &ctx.accounts.payer.to_account_info(),
        &ctx.accounts.system_program.to_account_info(),
        &crate::ID,
    )?;

    Ok(())
}
