// Auto-generated by compressible_instructions macro.
use anchor_lang::prelude::*;
use light_sdk::compressible::process_update_compression_config;

use crate::instruction_accounts::*;

pub fn update_compression_config(
    ctx: Context<UpdateCompressionConfig>,
    new_compression_delay: Option<u32>,
    new_rent_sponsor: Option<Pubkey>,
    new_address_space: Option<Vec<Pubkey>>,
    new_update_authority: Option<Pubkey>,
) -> Result<()> {
    process_update_compression_config(
        &ctx.accounts.config.to_account_info(),
        &ctx.accounts.authority.to_account_info(),
        new_update_authority.as_ref(),
        new_rent_sponsor.as_ref(),
        new_address_space,
        new_compression_delay,
        &crate::ID,
    )?;

    Ok(())
}
