// Seed functions are auto-generated by DeriveSeeds macro on the account types in state.rs
// This module just re-exports them for convenience

// CToken signer seeds - not tied to a state type so defined here
use anchor_lang::prelude::Pubkey;

pub use crate::state::{
    get_game_session_seeds, get_placeholder_record_seeds, get_user_record_seeds,
};

pub fn get_ctoken_signer_seeds(user: &Pubkey, mint: &Pubkey) -> (Vec<Vec<u8>>, Pubkey) {
    let seeds: &[&[u8]] = &[b"ctoken_signer", user.as_ref(), mint.as_ref()];
    let (pda, bump) = Pubkey::find_program_address(seeds, &crate::ID);
    let mut seeds_vec = Vec::with_capacity(seeds.len() + 1);
    for seed in seeds {
        seeds_vec.push(seed.to_vec());
    }
    seeds_vec.push(vec![bump]);
    (seeds_vec, pda)
}
