//! LightFinalize trait for compression finalization.
//!
//! This trait is implemented by the `#[derive(LightFinalize)]` macro from light-sdk-macros.
//! It provides a hook for running compression operations at the end of an instruction.

use solana_account_info::AccountInfo;

/// Trait for finalizing compression operations on accounts.
///
/// This is generated by `#[derive(LightFinalize)]` from light-sdk-macros.
/// Use with `#[light_instruction]` attribute for automatic invocation.
///
/// # Type Parameters
/// * `'info` - The account info lifetime
/// * `P` - The instruction params type (from `#[instruction(params: P)]`)
///
/// # Example
///
/// ```ignore
/// use anchor_lang::prelude::*;
/// use light_sdk::compressible::LightFinalize;
/// use light_sdk_macros::{LightFinalize, light_instruction};
///
/// #[derive(Accounts, LightFinalize)]
/// #[instruction(params: CompressionParams)]
/// pub struct CreateCompressible<'info> {
///     #[account(mut)]
///     pub fee_payer: Signer<'info>,
///     
///     #[account(mut)]
///     #[compressible(
///         address_tree_info = params.address_tree_info,
///         output_tree = 0
///     )]
///     pub my_account: Account<'info, MyData>,
///     
///     /// CHECK: Compression config
///     pub compression_config: AccountInfo<'info>,
/// }
///
/// // Auto-calls light_finalize at end of handler
/// #[light_instruction(params)]
/// pub fn create_compressible(ctx: Context<CreateCompressible>, params: CompressionParams) -> Result<()> {
///     ctx.accounts.my_account.value = params.value;
///     Ok(())
/// }
/// ```
pub trait LightFinalize<'info, P> {
    /// Execute compression finalization.
    ///
    /// This method is called at the end of an instruction to batch and execute
    /// all compression CPIs for accounts marked with `#[compressible(...)]`.
    ///
    /// # Arguments
    /// * `remaining_accounts` - The remaining accounts from the context, used for CPI
    /// * `params` - The instruction parameters containing compression data
    ///
    /// # Errors
    /// Returns an error if the compression CPI fails.
    fn light_finalize(
        &mut self,
        remaining_accounts: &[AccountInfo<'info>],
        params: &P,
    ) -> Result<(), crate::error::LightSdkError>;
}
