use anchor_lang::prelude::*;

/**
 * This file is auto-generated by the Light cli.
 * DO NOT EDIT MANUALLY.
 * THE FILE WILL BE OVERWRITTEN EVERY TIME THE LIGHT CLI BUILD IS RUN.
 */
#[allow(non_camel_case_types)]
// helper struct to create anchor idl with u256 type
#[account]
#[derive(Debug, Copy, PartialEq)]
pub struct u256 {
    pub x: [u8; 32],
}

pub const NR_CHECKED_INPUTS: usize = 26;

#[allow(non_snake_case)]
#[derive(Debug)]
#[account]
pub struct InstructionDataLightInstructionSecond {
    pub publicVoteWeightYesX: [u8; 32],
    pub publicVoteWeightYesY: [u8; 32],
    pub publicVoteWeightYesEmphemeralKeyX: [u8; 32],
    pub publicVoteWeightYesEmphemeralKeyY: [u8; 32],
    pub publicVoteWeightNoX: [u8; 32],
    pub publicVoteWeightNoY: [u8; 32],
    pub publicVoteWeightNoEmphemeralKeyX: [u8; 32],
    pub publicVoteWeightNoEmphemeralKeyY: [u8; 32],
    pub publicElGamalPublicKeyX: [u8; 32],
    pub publicElGamalPublicKeyY: [u8; 32],
    pub publicVoteEnd: [u8; 32],
    pub publicMint: [u8; 32],
    pub publicVoteWeightPspAddress: [u8; 32],
    pub voteWeightNullifier: [u8; 32],
    pub publicVoteId: [u8; 32],
    pub currentSlot: [u8; 32],
    pub publicOldVoteWeightYesX: [u8; 32],
    pub publicOldVoteWeightYesY: [u8; 32],
    pub publicOldVoteWeightYesEmphemeralKeyX: [u8; 32],
    pub publicOldVoteWeightYesEmphemeralKeyY: [u8; 32],
    pub publicOldVoteWeightNoX: [u8; 32],
    pub publicOldVoteWeightNoY: [u8; 32],
    pub publicOldVoteWeightNoEmphemeralKeyX: [u8; 32],
    pub publicOldVoteWeightNoEmphemeralKeyY: [u8; 32],
}

#[allow(non_snake_case)]
#[derive(Debug, Copy, PartialEq)]
#[account]
pub struct Utxo {
    pub amounts: [u64; 2],
    pub spl_asset_index: u64,
    pub verifier_address_index: u64,
    pub blinding: u256,
    pub app_data_hash: u256,
    pub account_shielded_public_key: u256,
    pub account_encryption_public_key: [u8; 32],
    pub voteWeight: u256,
    pub startSlot: u256,
    pub releaseSlot: u256,
    pub rate: u256,
    pub voteLock: u256,
    pub voteUtxoNumber: u256,
    pub voteUtxoIdNonce: u256,
    pub voteWeightPspAddress: u256,
}

#[allow(non_snake_case)]
#[account]
#[derive(Debug, Copy, PartialEq)]
pub struct UtxoAppData {
    pub voteWeight: u256,
    pub startSlot: u256,
    pub releaseSlot: u256,
    pub rate: u256,
    pub voteLock: u256,
    pub voteUtxoNumber: u256,
    pub voteUtxoIdNonce: u256,
    pub voteWeightPspAddress: u256,
}
